#!/bin/bash

# OpenSCAD Generator Demo Script
# This script demonstrates the functionality with sample outputs

set -e

# Configuration
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUTPUT_DIR="${SCRIPT_DIR}/demo_output"
LOGS_DIR="${OUTPUT_DIR}/logs"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}🚀 OpenSCAD Generator Demo${NC}"
echo -e "${BLUE}=========================${NC}"

# Create output directories
mkdir -p "${OUTPUT_DIR}"
mkdir -p "${LOGS_DIR}"

# Sample test cases with expected outputs
echo -e "\n${YELLOW}Demo Test Cases:${NC}"

# Test 1: Rounded Cube
echo -e "\n${GREEN}Test 1: Creating rounded cube with 25mm sides${NC}"
cat > "${OUTPUT_DIR}/rounded-cube-25.scad" << 'EOF'
// Generated by OpenSCAD Generator
// Prompt: create a rounded cube with 25mm sides
// Modules used: rounded_cube
// Default facets: 16

include <module.scad>;

// Parameters
size = [25, 25, 25];  // Cube dimensions in mm
radius = 3;           // Corner radius
facets = 16;          // Number of facets for rounded edges

// Create rounded cube
rounded_cube(size, radius, facets);
EOF
echo "✅ Generated: rounded-cube-25.scad"

# Test 2: Gear
echo -e "\n${GREEN}Test 2: Creating gear with 15 teeth${NC}"
cat > "${OUTPUT_DIR}/gear-15-teeth.scad" << 'EOF'
// Generated by OpenSCAD Generator
// Prompt: make a gear with 15 teeth and 5mm thickness
// Modules used: gear
// Default facets: 16

include <module.scad>;

// Gear parameters
number_of_teeth = 15;
circular_pitch = 200;
pressure_angle = 20;
gear_thickness = 5;
facets = 16;

// Create gear
linear_extrude(height = gear_thickness, center = true, $fn = facets) {
    gear(
        number_of_teeth = number_of_teeth,
        circular_pitch = circular_pitch,
        pressure_angle = pressure_angle
    );
}
EOF
echo "✅ Generated: gear-15-teeth.scad"

# Test 3: Code Modification
echo -e "\n${GREEN}Test 3: Modifying existing cube to add rounded edges${NC}"
cat > "${OUTPUT_DIR}/cube-rounded-15.scad" << 'EOF'
// Generated by OpenSCAD Generator
// Prompt: add rounded edges with 2mm radius
// Modules used: rounded_cube
// Default facets: 16
// Modification Type: code_modification

include <module.scad>;

// Original cube dimensions: 15x15x15
// Modified to add rounded edges
size = [15, 15, 15];  // [length, width, height] in mm
radius = 2;           // Corner radius (0-7.5 for this size)
facets = 16;          // Number of facets for rounded edges

// Create rounded cube
rounded_cube(size, radius, facets);

// Changes made from original code:
// 1. Replaced simple cube() with parameterized rounded_cube() module
// 2. Added adjustable corner radius parameter
// 3. Added facets parameter for smoothness control
EOF
echo "✅ Generated: cube-rounded-15.scad"

# Create summary logs
cat > "${LOGS_DIR}/summary.log" << 'EOF'
Demo Test Summary - $(date)
✅ SUCCESS: create a rounded cube with 25mm sides -> rounded-cube-25.scad
  Modules used: rounded_cube
  Generated lines: 12
✅ SUCCESS: make a gear with 15 teeth and 5mm thickness -> gear-15-teeth.scad
  Modules used: gear
  Generated lines: 18
✅ SUCCESS: add rounded edges with 2mm radius -> cube-rounded-15.scad
  Modules used: rounded_cube
  Generated lines: 21
  Modification type: code_modification
EOF

cat > "${LOGS_DIR}/modules_selection.log" << 'EOF'
Module Selection Analysis - $(date)
Test: create a rounded cube with 25mm sides
  Modules: rounded_cube
  Lines: 12
Test: make a gear with 15 teeth and 5mm thickness
  Modules: gear
  Lines: 18
Test: add rounded edges with 2mm radius
  Modules: rounded_cube
  Lines: 21
  Modification type: code_modification
EOF

# Create AI interactions log sample
cat > "${LOGS_DIR}/ai_interactions.log" << 'EOF'
OpenSCAD Generator Demo - $(date)
========================================
Test: create a rounded cube with 25mm sides
Output: rounded-cube-25.scad
Type: New Generation
Timestamp: $(date)
========================================
🎯 Processing prompt: "create a rounded cube with 25mm sides"
🔄 Starting OpenSCAD generation for prompt: "create a rounded cube with 25mm sides"
📋 Step 1: Selecting relevant modules...
Module selection result: rounded_cube
✅ Selected modules: rounded_cube
🔢 Step 2: Computing mathematical relationships...
📐 Mathematical computations completed
💻 Step 3: Generating OpenSCAD code...
✅ OpenSCAD generation completed successfully
💾 OpenSCAD code saved to: rounded-cube-25.scad

Test: make a gear with 15 teeth and 5mm thickness
Output: gear-15-teeth.scad
Type: New Generation
========================================
🎯 Processing prompt: "make a gear with 15 teeth and 5mm thickness"
🔄 Starting OpenSCAD generation for prompt: "make a gear with 15 teeth and 5mm thickness"
📋 Step 1: Selecting relevant modules...
Module selection result: gear
✅ Selected modules: gear
🔢 Step 2: Computing mathematical relationships...
📐 Mathematical computations completed
💻 Step 3: Generating OpenSCAD code...
✅ OpenSCAD generation completed successfully
💾 OpenSCAD code saved to: gear-15-teeth.scad

Test: add rounded edges with 2mm radius
Output: cube-rounded-15.scad
Type: Code Modification
Existing code: cube([15,15,15]);
========================================
🎯 Processing prompt: "add rounded edges with 2mm radius"
🔄 Starting OpenSCAD generation for prompt: "add rounded edges with 2mm radius"
📋 Step 1: Selecting relevant modules...
Module selection result: rounded_cube
✅ Selected modules: rounded_cube
🔢 Step 2: Computing mathematical relationships...
📐 Mathematical computations completed
💻 Step 3: Generating OpenSCAD code...
✅ OpenSCAD generation completed successfully
💾 OpenSCAD code saved to: cube-rounded-15.scad
EOF

# Create visual summary
cat > "${LOGS_DIR}/visual_summary.txt" << 'EOF'
╔══════════════════════════════════════════════════════════════════════╗
║              OpenSCAD Generator Demo Summary                          ║
╠══════════════════════════════════════════════════════════════════════╣
║ Total Tests: 3                                                   ║
║ Successful: 3                                                    ║
║ Failed: 0                                                        ║
║ Success Rate: 100.0%                                             ║
╚══════════════════════════════════════════════════════════════════════╝

Demo Execution Time: $(date)
Output Directory: ${OUTPUT_DIR}
Logs Directory: ${LOGS_DIR}

Generated Files:
3 OpenSCAD files created
~2KB total size

Module Usage Summary:
rounded_cube: 2 tests
gear: 1 test

Test Types:
- New Generation: 2 tests
- Code Modification: 1 test

Features Demonstrated:
✅ Module selection from modules_list.json
✅ Mathematical computation for dimensions
✅ Parameterized OpenSCAD code generation
✅ Existing code modification capabilities
✅ Comprehensive logging and analysis
✅ File output to organized directory structure

For detailed analysis, see:
- ${LOGS_DIR}/summary.log
- ${LOGS_DIR}/modules_selection.log
- ${LOGS_DIR}/ai_interactions.log
EOF

# Display results
echo -e "\n${BLUE}📁 Generated Files:${NC}"
ls -la "${OUTPUT_DIR}"/*.scad

echo -e "\n${BLUE}📊 Demo Summary:${NC}"
cat "${LOGS_DIR}/visual_summary.txt"

echo -e "\n${GREEN}✨ Demo completed successfully!${NC}"
echo -e "${GREEN}Generated files: ${OUTPUT_DIR}${NC}"
echo -e "${GREEN}Detailed logs: ${LOGS_DIR}${NC}"
echo -e "${YELLOW}Note: This is a demo showing the expected output format.${NC}"
echo -e "${YELLOW}In production, replace with valid DeepSeek API key.${NC}"
