apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: promptscad
  name: promptscad
spec:
  replicas: 1
  selector:
    matchLabels:
      app: promptscad
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: promptscad
    spec:
      containers:
      - image: ahmadsayed/promptscad:10
        name: promptscad
        ports:
        - containerPort: 3000
        env:
        - name: DEEPSEEK_API_KEY
          valueFrom:
            secretKeyRef:
              name: deepseek-api-key
              key: DEEPSEEK_API_KEY        
        resources: {}
---
apiVersion: v1
kind: Service
metadata:
  name: promptscad
  labels:
    app: promptscad
spec:
  selector:
    app: promptscad
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: promptscad
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  ingressClassName: traefik
  rules:
  - host: promptscad.com
    http:
      paths:   
      - path: /
        pathType: Prefix
        backend:
          service:
            name: promptscad
            port:
              number: 80