apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: promptscad-www
  namespace: default
spec:
  ingressClassName: traefik
  rules:
  - host: www.promptscad.com
    http:
      paths:
      - backend:
          service:
            name: promptscad
            port:
              number: 80
        path: /
        pathType: Prefix
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: promptscad
  namespace: default
spec:
  ingressClassName: traefik
  rules:
  - host: promptscad.com
    http:
      paths:
      - backend:
          service:
            name: promptscad
            port:
              number: 80
        path: /
        pathType: Prefix
        