---
# Middleware for redirect
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: ads-txt-redirect
  namespace: default
spec:
  redirectScheme:
    scheme: https
    permanent: true
    port: 443
    host: "srv.adstxtmanager.com"
    path: "/19390/promptscad.com"
---
# Dummy service (required placeholder)
apiVersion: v1
kind: Service
metadata:
  name: dummy-service
  namespace: default
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080      
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: promptscad
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  ingressClassName: traefik
  rules:
  - host: promptscad.com
    http:
      paths:    
      - path: /
        pathType: Prefix
        backend:
          service:
            name: promptscad
            port:
              number: 80